### ISSUE TITLE
Ability to specify chmod of file copied via provision file

### ISSUE THREAD

**Issue by krzysztof-magosa** [vagrant-dotvm/vagrant-dotvm#11]

**Comment by jhcook** [comment]
Shouldn't provision mechanisms such as Ansible, Puppet or shell be able to set a files mode? I know they do; so, I'm curious what a use case for this is.

**Comment by krzysztof-magosa** [comment]
We use vagrant `file` provision for example to copy ssh keys from host to guest machine. It works nice on UNIX host systems, but when host is on windows then file has 0777 permissions after copying and ssh rejects unsecure key. I'm not sure how this option will be done. Maybe just by chmod via scriptlets.

**Comment by jhcook** [comment]
That’s interesting if using the config object in Vagrant.

**Comment by krzysztof-magosa** [comment]
https://docs.vagrantup.com/v2/provisioning/file.html

At the moment I'll set this issue as `won't fix` because since i've added inline shell it can be done by just issuing normal chmod command.
