### ISSUE TITLE
Ability to persist network options inside guest vm

### ISSUE THREAD

**Issue by krzysztof-magosa** [vagrant-dotvm/vagrant-dotvm#13]
After restarting network stack using tools builtin in guest OS configuration of interfaces, added routes etc. is lost. This ticket is about adding functionality which can persist this configuration in guest OS specific way. For the first instance there will be support for RedHat derivatives with major focus on CentOS 6/7.

**Comment by jhcook** [comment]
Is this something you'd prefer me to work on?

**Comment by krzysztof-magosa** [comment]
I would really appreciate preparing shell script creating configuration in proper place, based on given parameters. Then plugging it into Ruby will be simple task.

**Comment by jhcook** [comment]
Yeah that's pretty straightforward and reusable. I can get started on that as soon as I get back.

**Comment by jhcook** [comment]
After looking into this initially, we need to support Linux, Solaris and AIX. I do not have access to AIX hosts to test on, so it will have to be a stub at the moment. In the Linux case, we should follow LSB for identifying release and versions. I have found a template from 2005 that supports these cases and have tested it on RHEL6. I received a positive result, so this should be something good to start with. There are more complicated, lengthy solutions out there, but they will be unnecessary for this. 

http://www.unix.com/unix-for-advanced-and-expert-users/21468-machine.html#post83185
https://www.linuxbase.org/lsb-cert/productdir.php?by_lsb

The easiest method would be to require `lsb_core` which is provided by "redhat-lsb-core" but is not installed by default:

http://refspecs.linuxbase.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/lsbrelease.html

**Comment by krzysztof-magosa** [comment]
I'm pretty sure Vagrant does some guest OS detection to do internal things like mounting shared folders. I will check and let you know because maybe we will be able to get this info from Vagrant.

**Comment by krzysztof-magosa** [comment]
Please create at the moment script which just works on selected distribution, I will try to do OS detection on Vagrant level.

**Comment by krzysztof-magosa** [comment]
This won't be progressed unless somebody sends pull request.
