### ISSUE TITLE
Vagrantfile dir is not mounted to /vagrant in guest

### ISSUE THREAD

**Issue by jhcook** [vagrant-dotvm/vagrant-dotvm#3]
During provisioning, the /vagrant dir is not mounted, but by default it is normally available. However, it is not and requires specifying in the YAML file:

==> someguest01: + mount -t vboxsf -o uid=500,gid=500 vagrant /vagrant
==> someguest01: /sbin/mount.vboxsf: mounting failed with the error
==> someguest01: : No such file or directory

The fix:
    shared_folders:
      - host: "."
        guest: "/vagrant"

**Comment by jhcook** [comment]
/vagrant being available should be the default behaviour.

**Comment by krzysztof-magosa** [comment]
I think that would be better to use /dotvm/project where only project related files are available to avoid relations between projects. But if you really need it, then I will make it available. Please update to 0.10.0.

**Comment by jhcook** [comment]
Thanks! I understand the different URL, but this should be as transparent as possible. Since it extends Vagrant, it should "conform" as closely as possible so it's a drop-in replacement.

**Comment by krzysztof-magosa** [comment]
Ok, I agree with that.
