### ISSUE TITLE
Kernel Command-line args

### ISSUE THREAD

**Issue by jhcook** [vagrant-dotvm/vagrant-dotvm#44]
If you look here:

https://wiki.centos.org/FAQ/CentOS7

You will see a valid use case for passing kernel command line args. This would be great to support.

**Comment by krzysztof-magosa** [comment]
I've grepped Vagrant documentation and from what I know it does not allow to pass kernel parameters.
Because DotVM is just interface to Vagrant I'm not able to add this feature.
